RunEnv = 'development'

[ObjectStorage1]
AccessKeyID = 'Q3AM3UQ867SPQQA43P2F'
Endpoint = 'play.min.io'
SecretAccessKey = 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
UseSSL = true

[MessageBroker1]
URI = 'amqp://user:bitnami@localhost:5672/%2f'

[MessageBroker1.ExchangesQueues.Tracking.Exchange]
AutoDeleted = false
Durable = true
Internal = false
Name = "fanout-tracking-frontend"
NoWait = false
Type = "fanout"

[MessageBroker1.ExchangesQueues.Tracking.Queue]
AutoDeleted = false
Durable = true
Exclusive = false
Name = "tracking-frontend-svc-beckend-digestion-store"
NoWait = false

[MessageBroker1.ExchangesQueues.Tracking.Queue.Arguments]
# 1 Gigabyte
"x-max-length-bytes" = 1073741824
# 1 million
"x-max-length" = 1000000
